# https://github.com/caksoylar/keymap-drawer

layout: {ortho_layout: {split: true, rows: 3, columns: 5, thumbs: 2}}
layers:
  BASE:
    - [Q, W, F, P, B, J, L, U, Y, "'"]
    - [{h: Shift, t: A}, {h: Alt, t: R}, {h: Ctrl, t: S}, {h: GUI, t: T}, G, M, {h: GUI, t: N}, {h: Ctrl, t: E}, {h: Alt, t: I}, {h: Shift, t: O}]
    - [Z, X, C, D, V, K, H, {s: ;, t: ","}, {s: ":", t: .}, {s: \, t: /}]
    - [{h: Ctrl, t: Space}, Shift, {h: NAV, t: BASE}, SYM]
  SYM:
    - ["?", "@", "#", "$", null, "|", "%", "*", "^", "&"]
    - ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]
    - ["+", "=", {s: "[", t: "{"}, {s: "]", t: "}"}, {s: "`", t: "~"}, "!", {s: "<", t: "("}, {s: "<", t: ")"}, "-", "_"]
    - [null, null, null, {type: held}]
  NAV:
    - [ESC, null, null, null, null, null, ESC, TAB, DEL, BSPC]
    - [Shift, Alt, Ctrl, Gui, null, Left, Down, Up, Right, Enter]
    - [FN, null, null, null, null, Home, PgDN, PgUp, End, null]
    - [null, null, {type: held}, null]
  FUN:
    - [null, "Vol-", "Vol+", F11, null, null, F12, "Bri-", "Bri+", null]
    - [F1, F2, F3, F4, F5, F6, F7, F8, F9, F10]
    - [null, null, "BT Prev", "BT Next", "BT Clear", BT1, BT2, BT3, null, null]
    - [null, null, null, null]
combos:
  - {p: [12, 13], k: "ESC", l: ["BASE"]}
  - {p: [11, 12], k: "TAB", l: ["BASE"]}
  - {p: [16, 17], k: "ESC", l: ["BASE"]}
