manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: smchunn
      url-base: https://github.com/smchunn

  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
      revision: main

    - name: zmk-keyboards-smcboard40
      remote: smchunn
      revision: main

  self:
    path: config
